# Generated by Django 5.0.2 on 2024-02-21 17:20

import authentication.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0002_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="password",
            field=models.CharField(
                max_length=25,
                validators=[
                    authentication.models.validate_password,
                    django.core.validators.MinLengthValidator(8),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                max_length=25,
                unique=True,
                validators=[
                    authentication.models.validate_username,
                    django.core.validators.MinLengthValidator(6),
                ],
            ),
        ),
    ]
