# Generated by Django 5.0.1 on 2024-01-07 16:31

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_created", models.DateField(auto_now_add=True)),
                ("date_updated", models.DateField(auto_now=True)),
                (
                    "date_from",
                    models.DateField(
                        default=django.utils.timezone.localdate,
                        help_text="e.g. 05/09/2023",
                        verbose_name="Date from: ",
                    ),
                ),
                (
                    "date_to",
                    models.DateField(
                        default=datetime.date(2024, 2, 6),
                        help_text="eg. 05/10/2023",
                        verbose_name="Date to:",
                    ),
                ),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total Income"
                    ),
                ),
                (
                    "housing",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Housing Costs"
                    ),
                ),
                (
                    "utility_bills",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Utility Bills"
                    ),
                ),
                (
                    "food_drinks",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Food and Drinks Groceries",
                    ),
                ),
                (
                    "transport",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Transport Costs"
                    ),
                ),
                (
                    "household_goods_services",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Household Goods and Services",
                    ),
                ),
                (
                    "children_related_costs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Children Related Costs",
                    ),
                ),
                (
                    "cleaning_toiletries",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Cleaning and Toiletries",
                    ),
                ),
                (
                    "other_essential_costs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Other Essential Costs",
                    ),
                ),
                (
                    "luxury_gifts",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Luxury and Gifts"
                    ),
                ),
                (
                    "leisure_entertainment",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Leisure & Entertainment",
                    ),
                ),
                (
                    "holidays",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Holidays and Travel",
                    ),
                ),
                (
                    "other_non_essential_costs",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Other Non-Essential Costs",
                    ),
                ),
                (
                    "unsecured_loans",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Unsecured Loans (Credit Cards, Store Cards, Payday Loans)",
                    ),
                ),
                (
                    "total_essential",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Essential Expenses",
                    ),
                ),
                (
                    "total_non_essential",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Non-Essential Expenses",
                    ),
                ),
                (
                    "total_expenses",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Expenses",
                    ),
                ),
                (
                    "total_savings",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=20,
                        verbose_name="Total Savings",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
