# Generated by Django 5.0.1 on 2024-01-17 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="date_to",
            field=models.DateField(
                default=datetime.date(2024, 2, 16),
                help_text="eg. 05/10/2023",
                verbose_name="Date to:",
            ),
        ),
    ]
