# Generated by Django 4.2.5 on 2023-09-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="month_year",
            field=models.DateField(
                default=" 05 September 2023",
                help_text="e.g. 05 September 2023))",
                unique=True,
                verbose_name="Day Month and Year",
            ),
        ),
    ]
