# Generated by Django 4.2.5 on 2023-09-05 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="day_month_year",
            field=models.DateField(
                default=datetime.date(2023, 9, 5),
                help_text="e.g. 05/09/2023))",
                unique=True,
                verbose_name="Day Month and Year",
            ),
        ),
    ]
