# Generated by Django 5.0.1 on 2024-01-29 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0002_alter_budget_date_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="charity",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Charitable contributions",
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="date_to",
            field=models.DateField(
                default=datetime.date(2024, 2, 28),
                help_text="eg. 05/10/2023",
                verbose_name="Date to:",
            ),
        ),
    ]
