# Generated by Django 4.2.6 on 2023-10-19 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0002_rename_user_id_budget_user_identifier_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="user_identifier",
            new_name="user_id",
        ),
        migrations.AlterField(
            model_name="budget",
            name="day_month_year",
            field=models.DateField(
                default=datetime.date(2023, 10, 19),
                help_text="e.g. 05/09/2023))",
                verbose_name="Day Month and Year",
            ),
        ),
    ]
