# Generated by Django 4.2.6 on 2023-11-14 15:52

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0003_rename_user_identifier_budget_user_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="budget",
            name="day_month_year",
        ),
        migrations.AddField(
            model_name="budget",
            name="date_from",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                help_text="e.g. 05/09/2023",
                verbose_name="Date from: ",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="date_to",
            field=models.DateField(
                default=datetime.date(2023, 12, 14),
                help_text="eg. 05/10/2023",
                verbose_name="Date to:",
            ),
        ),
    ]
