# Generated by Django 4.2.6 on 2023-12-12 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "budget_planner",
            "0004_remove_budget_day_month_year_budget_date_from_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="budget",
            name="total_essential",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Essential Expenses",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="total_expenses",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Expenses",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="total_non_essential",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Total Non-Essential Expenses",
            ),
        ),
        migrations.AddField(
            model_name="budget",
            name="total_savings",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Savings"
            ),
        ),
        migrations.AlterField(
            model_name="budget",
            name="date_to",
            field=models.DateField(
                default=datetime.date(2024, 1, 11),
                help_text="eg. 05/10/2023",
                verbose_name="Date to:",
            ),
        ),
    ]
