# Generated by Django 5.0.2 on 2024-02-21 17:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("budget_planner", "0004_alter_budget_date_to"),
    ]

    operations = [
        migrations.AlterField(
            model_name="budget",
            name="date_to",
            field=models.DateField(
                default=datetime.date(2024, 3, 22),
                help_text="eg. 05/10/2023",
                verbose_name="Date to:",
            ),
        ),
    ]
